### ISSUE TITLE
AttributeError: 'RconConnection' object has no attribute 'pkt_id'

### ISSUE THREAD

**Issue by lavacano201014** [pmrowla/pysrcds#3]
From interpreter:

```
>>> server = srcds.rcon.RconConnection("server.address.redacted", password="BadPass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/srcds/rcon.py", line 51, in __init__
    self._authenticate(password)
  File "/usr/lib64/python2.7/site-packages/srcds/rcon.py", line 56, in _authenticate
    auth_pkt = RconPacket(self.pkt_id.next(), SERVERDATA_AUTH, password)
AttributeError: 'RconConnection' object has no attribute 'pkt_id'
```

fails in both python2 and python3

**Comment by pmrowla** [comment]
i think this should have been resolved in #4
